language: node_js
node_js:
  - "0.10"

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm config set spin false
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

addons:
    code_climate:
        repo_token: 05a539ae0b844fcc943a618503f09e58fb6f1ce008d321b6987534e5bac2efbb