language: node_js
node_js:
  - "0.10"

cache:
  directories:
    - node_modules
    - bower_components

before_script:
  - npm config set spin false
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install