dist: trusty
sudo: required

language: node_js
node_js:
  - 4

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - $HOME/.cache/bower
    - node_modules
    - bower_components

before_install:
  # Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version
  # Bower
  - yarn global add bower
  # Grunt
  - yarn global add grunt-cli

addons:
    code_climate:
        repo_token: 05a539ae0b844fcc943a618503f09e58fb6f1ce008d321b6987534e5bac2efbb